# SEO
title: Spleenftw experiences
description: A bold typographic theme inspired by Swiss design.
social_link: twitter
social_username: spleenftw
github_repo: spleenftweb # the GitHub repo name for your project
github_username: spleenftw
theme_color: black
remote_theme: internet-de-france/swiss
baseurl: /spleenftweb

defaults:
  - scope:
      path: ''
      type: pages
    values:
      category_name: ''
  - scope:
      path: ''
      type: posts
    values:
      categories: ''

remote_theme_layouts:
  - ''
  - default
  - page
  - post
  - home
  - category_index

social_links:
  - twitter

theme_colors:
  - black
  - blue
  - gray
  - magenta
  - orange
  - red
  - white
  - yellow
